version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sns
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      - mysql-data:/var/lib/mysql
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
  bull-redis:
    image: redis:latest
    ports:
      - '6380:6380'
    volumes:
      - redis-data:/data
    command: redis-server --port 6380 --appendonly yes
  minio:
    image: minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    volumes:
      - minio-data:/data
    command: 'server /data --console-address ":9001"'

volumes:
  mysql-data:
  redis-data:
  minio-data:
