version: 2.1
orbs:
  node: circleci/node@5.2.0

jobs:
  build_and_test:
    docker:
      - image: cimg/node:20.11.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test:e2e
          name: Run tests

workflows:
  test_my_app:
    jobs:
      - build_and_test:
          filters:
            branches:
              only:
                - develop