version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable # 使用するDockerイメージ
    steps:
      - checkout
      - run:
          name: Hello World
          command: |
            echo "Hello World"

workflows:
  version: 2
  build_on_develop:
    jobs:
      - build:
          filters:
            branches:
              only: develop
