version: 2.1
orbs:
  node: circleci/node@5.2.0

jobs:
  build_and_test:
    docker:
      - image: cimg/node:20.11.0
      - image: cimg/mysql:8.0
        command: |
          mysqld --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_DATABASE: sns_test
          MYSQL_HOST: 127.0.0.1
          MYSQL_ROOT_PASSWORD: 'password'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test
          name: Run tests

workflows:
  test:
    jobs:
      - build_and_test:
          filters:
            branches:
              only:
                - develop
